location /uploads/ {
  client_max_body_size 10m;

  mirror /_big_brother_scan;
  proxy_pass http://app_backend;
}

location = /_big_brother_scan {
  internal;
  proxy_method POST;
  proxy_pass http://big_brother_api:8080/v1/scan;
  proxy_set_header Content-Type $content_type;
}
